import { SalesforceOrgUi } from '@jetstream/types';

export const TEST_ORG_DEFAULT: SalesforceOrgUi = {
  uniqueId: '00DDn00000ACjIMMA1-005Dn000004b2k2IAA',
  accessToken: '',
  label: 'jetstream-test-1@getjetstream.app',
  filterText: 'jetstream-test-1@getjetstream.appjetstream-test-1jetstream-test-1@getjetstream.app',
  instanceUrl: 'https://jetstream-test-1-dev-ed.develop.my.salesforce.com',
  loginUrl: 'https://login.salesforce.com',
  userId: '005Dn000004b2k2IAA',
  email: 'paustint@gmail.com',
  organizationId: '00DDn00000ACjIMMA1',
  username: 'jetstream-test-1@getjetstream.app',
  displayName: 'Jestream Support',
  thumbnail: 'https://jetstream-test-1-dev-ed.develop.file.force.com/profilephoto/005/T',
  apiVersion: null,
  orgName: 'jetstream-test-1',
  orgCountry: 'US',
  orgOrganizationType: 'Developer Edition',
  orgInstanceName: 'NA224',
  orgIsSandbox: false,
  orgLanguageLocaleKey: 'en_US',
  orgNamespacePrefix: null,
  orgTrialExpirationDate: null,
  color: '#60A5FA',
  connectionError: null,
  createdAt: '2023-02-12T14:17:49.338Z',
  updatedAt: '2023-04-09T12:17:44.830Z',
};
